# Generated by Django 4.2.7 on 2023-11-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='titleeeeeee',
        ),
    ]
